all:	infinite alarmClock clock showCmdArg

infinite: infinite.c
	gcc -Wall -o infinite infinite.c

alarmClock: alarmClock.c
	gcc -Wall -o alarmClock alarmClock.c

clock:	clock.c
	gcc -Wall -o clock clock.c

showCmdArg:	showCmdArg.c
	gcc -Wall -o showCmdArg showCmdArg.c
